"""Universal-modder inspired families: the game-modding methodology.

The methodology (recon -> safe lab -> read the real code -> one slice ->
oracle -> package) comes from the public universal-modder project by
rehan_shei (Sep 2026). Everything here is executed on SYNTHETIC data
generated by this pipeline: no proprietary formats, no real game files,
no real installs.

Families:
  game_engine_recon   - fingerprint a synthetic install manifest (engine,
                        loader, anti-cheat, online) and pick a modding route.
  game_save_backup    - snapshot / diff / restore save folders with sha256
                        integrity gates (the `um backup` model).
  game_publish_lint   - lint a synthetic mod package for content that must
                        never ship (game files, leaked keys, decompiler
                        artifacts, absolute paths).
  game_oracle_replay  - trace-replay oracle: an f32-quantized toy sim is
                        replayed against a recorded trace and the first
                        divergence is reported.
"""
from __future__ import annotations

import hashlib
import random
import struct

from ..core import Candidate, Family, register


# ---------------------------------------------------------- shared helpers
def _f32(v: float) -> float:
    """Quantize to IEEE-754 single precision (game engines store f32)."""
    return struct.unpack("<f", struct.pack("<f", v))[0]


def _entry(rng: random.Random, path: str, head_hex: str,
           strings: list[str] | None = None) -> dict:
    """One manifest row of a synthetic install tree."""
    return {"path": path, "size": rng.randrange(4_000, 900_000_000),
            "head_hex": head_hex + "".join(rng.choice("0123456789ABCDEF")
                                           for _ in range(8)),
            "strings": strings or []}


def _decoys(rng: random.Random, game: str, count: int) -> list[dict]:
    """Harmless files that must not trip any detection rule."""
    pool = [f"{game}/logs/client.log", f"{game}/screenshots/clip.png",
            f"{game}/credits.odt", f"{game}/shaders/base.frag",
            f"{game}/localization/en.json", f"{game}/manual.pdf"]
    rng.shuffle(pool)
    out = []
    for p in pool[:count]:
        out.append(_entry(rng, p, ""))
    return out


# ================================================================ 1. recon
_RECON_GAME_NAMES = ["Starfall", "Ironvale", "Nebula Drift", "Clockwork Exile",
                     "Frostline", "Ashen Marches", "Vault Runners"]

# engine -> (evidence builder, has_data_formats, managed)
def _plant_engine(rng: random.Random, engine: str, game: str) -> list[dict]:
    if engine == "godot":
        return [_entry(rng, f"{game}/main.pck", "47445043",
                       ["Godot Engine v4.3"]),
                _entry(rng, f"{game}/{game}.exe", "4D5A")]
    if engine == "unity-mono":
        return [_entry(rng, f"{game}/{game}_Data/globalgamemanagers",
                       "556E6974794653"),
                _entry(rng, f"{game}/{game}_Data/Managed/Assembly-CSharp.dll",
                       "4D5A", ["UnityPlayer.dll"]),
                _entry(rng, f"{game}/{game}.exe", "4D5A")]
    if engine == "unity-il2cpp":
        return [_entry(rng, f"{game}/{game}_Data/il2cpp_data/Metadata/"
                              "global-metadata.dat", "AF1BB1FA"),
                _entry(rng, f"{game}/{game}_Data/GameAssembly.dll", "4D5A",
                       ["GameAssembly.dll"])]
    if engine == "unreal":
        return [_entry(rng, f"{game}/Content/Paks/{game}-Windows.pak",
                       "E1126F5A"),
                _entry(rng, f"{game}/{game}/Binaries/Win64/{game}-Win64.exe",
                       "4D5A", ["Engine/Binaries/ThirdParty"]),
                _entry(rng, f"{game}/Engine/Binaries/ThirdParty/Ogg.dll",
                       "4D5A")]
    if engine == "xna-fna":
        return [_entry(rng, f"{game}/FNA.dll", "4D5A", ["FNA3D"]),
                _entry(rng, f"{game}/Content/Sprites.xnb", "584E4277"),
                _entry(rng, f"{game}/{game}.exe", "4D5A")]
    if engine == "gamemaker":
        return [_entry(rng, f"{game}/data.win", "464F524D",
                       ["GameMaker Studio 2"]),
                _entry(rng, f"{game}/{game}.exe", "4D5A")]
    if engine == "java":
        return [_entry(rng, "versions/1.21.1/1.21.1.jar", "504B0304"),
                _entry(rng, "libraries/net/fabricmc/fabric-loader/0.16.9/"
                            "fabric-loader-0.16.9.jar", "504B0304",
                       ["fabric-loader"])]
    raise ValueError(engine)


def _plant_loader(rng: random.Random, loader: str) -> list[dict]:
    if loader == "bepinex":
        return [_entry(rng, "BepInEx/core/BepInEx.Core.dll", "4D5A"),
                _entry(rng, "doorstop_config.ini", "", ["winhttp.dll"])]
    if loader == "ue4ss":
        return [_entry(rng, "ue4ss/UE4SS.dll", "4D5A"),
                _entry(rng, "ue4ss/Mods/mods.txt", "")]
    if loader == "tmodloader":
        return [_entry(rng, "tModLoader.dll", "4D5A", ["tModLoader"])]
    if loader == "fabric":
        return [_entry(rng, "mods/fabric.mod.json", "7B",
                       ["fabricloader"])]
    if loader == "smapi":
        return [_entry(rng, "Mods/SMAPI.dll", "4D5A", ["SMAPI"])]
    raise ValueError(loader)


def _plant_anticheat(rng: random.Random, ac: str) -> list[dict]:
    if ac == "battleye":
        return [_entry(rng, "BEService_x64.dll", "4D5A")]
    if ac == "eac":
        return [_entry(rng, "EasyAntiCheat/EasyAntiCheat_x64.dll", "4D5A")]
    return []


_ONLINE_STRINGS = ["OnlineSubsystemSteam", "EOS_SDK", "PlayFab"]


def _recon_decide(manifest: list[dict]) -> dict:
    """Reference decision table (single source of truth for ground truth)."""
    paths = [e["path"].replace("\\", "/").lower() for e in manifest]
    heads = [e["head_hex"].lower() for e in manifest]
    strings = {s.lower() for e in manifest for s in e.get("strings", [])}
    online = bool(strings & {s.lower() for s in _ONLINE_STRINGS})
    if any(h.startswith("47445043") for h in heads):
        engine = "godot"
    elif (any("global-metadata.dat" in p for p in paths)
          and any("gameassembly.dll" in p for p in paths)):
        engine = "unity-il2cpp"
    elif any(h.startswith("556e6974794653") or "globalgamemanagers" in p
             for h, p in zip(heads, paths)):
        engine = "unity-mono"
    elif any(h.startswith("e1126f5a") for h in heads):
        engine = "unreal"
    elif (any(h.startswith("584e42") for h in heads)
          and any(p.endswith("fna.dll") for p in paths)):
        engine = "xna-fna"
    elif any(p.endswith("data.win") and h.startswith("464f524d")
             for h, p in zip(heads, paths)):
        engine = "gamemaker"
    elif any(p.startswith("versions/") and p.endswith(".jar") for p in paths):
        engine = "java"
    else:
        engine = "unknown"
    if any(p.startswith("bepinex/core/") for p in paths):
        loader = "bepinex"
    elif any(p == "ue4ss/ue4ss.dll" for p in paths):
        loader = "ue4ss"
    elif any(p.endswith("tmodloader.dll") for p in paths):
        loader = "tmodloader"
    elif "mods/fabric.mod.json" in paths:
        loader = "fabric"
    elif any(p == "mods/smapi.dll" for p in paths):
        loader = "smapi"
    else:
        loader = None
    if any(p.endswith("beservice_x64.dll") for p in paths):
        anti_cheat = "battleye"
    elif any("easyanticheat" in p for p in paths):
        anti_cheat = "eac"
    else:
        anti_cheat = "none"
    if anti_cheat != "none" and online:
        route = "refuse-online"
    elif loader is not None:
        route = "loader-api"
    elif engine in ("godot", "gamemaker", "java"):
        route = "data"
    elif engine in ("unity-mono", "xna-fna"):
        route = "managed-patch"
    else:
        route = "native-hook"
    return {"engine": engine, "loader": loader, "anti_cheat": anti_cheat,
            "online": online, "route": route}


_RECON_TEMPLATE = '''def classify_install(manifest):
    """Fingerprint a game install from a bounded file manifest.

    Decision table (game-recon): engine by distinctive magic/marker evidence;
    community loader if present; anti-cheat; online flags from engine
    strings. Route ladder: refuse (anti-cheat + online) > loader-api >
    data > managed-patch > native-hook.
    """
    paths = [e["path"].replace("\\\\", "/").lower() for e in manifest]
    heads = [e["head_hex"].lower() for e in manifest]
    strings = {s.lower() for e in manifest for s in e.get("strings", [])}
    online = bool(strings & {"onlinesubsystemsteam", "eos_sdk", "playfab"})
    if any(h.startswith("47445043") for h in heads):
        engine = "godot"
    elif (any("global-metadata.dat" in p for p in paths)
          and any("gameassembly.dll" in p for p in paths)):
        engine = "unity-il2cpp"
    elif any(h.startswith("556e6974794653") or "globalgamemanagers" in p
             for h, p in zip(heads, paths)):
        engine = "unity-mono"
    elif any(h.startswith("e1126f5a") for h in heads):
        engine = "unreal"
    elif (any(h.startswith("584e42") for h in heads)
          and any(p.endswith("fna.dll") for p in paths)):
        engine = "xna-fna"
    elif any(p.endswith("data.win") and h.startswith("464f524d")
             for h, p in zip(heads, paths)):
        engine = "gamemaker"
    elif any(p.startswith("versions/") and p.endswith(".jar") for p in paths):
        engine = "java"
    else:
        engine = "unknown"
    if any(p.startswith("bepinex/core/") for p in paths):
        loader = "bepinex"
    elif any(p == "ue4ss/ue4ss.dll" for p in paths):
        loader = "ue4ss"
    elif any(p.endswith("tmodloader.dll") for p in paths):
        loader = "tmodloader"
    elif "mods/fabric.mod.json" in paths:
        loader = "fabric"
    elif any(p == "mods/smapi.dll" for p in paths):
        loader = "smapi"
    else:
        loader = None
    if any(p.endswith("beservice_x64.dll") for p in paths):
        anti_cheat = "battleye"
    elif any("easyanticheat" in p for p in paths):
        anti_cheat = "eac"
    else:
        anti_cheat = "none"
    if anti_cheat != "none" and online:
        route = "refuse-online"
    elif loader is not None:
        route = "loader-api"
    elif engine in ("godot", "gamemaker", "java"):
        route = "data"
    elif engine in ("unity-mono", "xna-fna"):
        route = "managed-patch"
    else:
        route = "native-hook"
    return {"engine": engine, "loader": loader, "anti_cheat": anti_cheat,
            "online": online, "route": route}
'''


class GameEngineReconFamily(Family):
    NAME = "game_engine_recon"
    LANGUAGE = "python"
    DOMAIN = "systems"
    DIFFICULTIES = ("intermediate", "advanced")
    SUPPORTS = ("explanation", "debugging", "testing", "code_review")

    _SCENARIOS = [
        ("godot", "bepinex", "none", False),
        ("unity-mono", None, "eac", False),
        ("unreal", None, "battleye", True),
        ("xna-fna", "tmodloader", "none", False),
        ("gamemaker", None, "none", False),
        ("unity-il2cpp", None, "none", False),
        ("java", "fabric", "none", False),
        ("godot", "ue4ss", "none", True),
        ("unity-mono", "smapi", "battleye", True),
    ]

    def generate(self, rng: random.Random) -> Candidate:
        game = rng.choice(_RECON_GAME_NAMES)
        picked = rng.sample(self._SCENARIOS, 5)
        manifests = []
        for engine, loader, ac, online in picked:
            entries = _plant_engine(rng, engine, game)
            if loader:
                entries += _plant_loader(rng, loader)
            if ac != "none":
                entries += _plant_anticheat(rng, ac)
            if online:
                e = rng.choice(entries)
                e["strings"] = list(e["strings"]) + [
                    rng.choice(_ONLINE_STRINGS)]
            entries += _decoys(rng, game, rng.randint(2, 3))
            rng.shuffle(entries)
            manifests.append(entries)
        expecteds = [_recon_decide(m) for m in manifests]
        tests_parts = []
        for i, (m, exp) in enumerate(zip(manifests, expecteds)):
            tests_parts.append(
                f"    m{i} = {m!r}\n"
                f"    assert classify_install(m{i}) == {exp!r}\n")
        tests = "def run_tests():\n" + "\n".join(tests_parts) + \
            "    assert classify_install([]) == {'engine': 'unknown', " \
            "'loader': None, 'anti_cheat': 'none', 'online': False, " \
            "'route': 'native-hook'}\n"
        expected = ("Every planted install is classified exactly: engine from "
                    "magic/marker evidence, loader, anti-cheat, online flags, "
                    "and the route follows the refuse > loader-api > data > "
                    "managed-patch > native-hook ladder.")
        explain = {
            "purpose": ("Fingerprint a game install and choose the cheapest "
                        "safe modding route before writing any mod code."),
            "approach": ("Collect lowercase path/head/string evidence once, "
                         "match engine magics in priority order, then walk "
                         "the route ladder."),
            "key_points": ["magic bytes beat file names (paks/pck/data.win)",
                           "the refuse rule (anti-cheat AND online) precedes "
                           "every other route",
                           "a loader always wins over manual patching"],
            "big_o_time": "O(n) over manifest entries per rule group",
            "big_o_space": "O(n)",
            "edge_cases": ["empty manifest", "several engines' launchers",
                           "anti-cheat without online", "loader + anti-cheat"]}
        bugs = {
            "offline_refused": lambda fs: {
                "solution.py": fs["solution.py"].replace(
                    'if anti_cheat != "none" and online:',
                    'if anti_cheat != "none" or online:')},
            "route_ladder_swapped": lambda fs: {
                "solution.py": fs["solution.py"].replace(
                    'elif engine in ("godot", "gamemaker", "java"):',
                    'elif engine in ("godot", "gamemaker", "java") and False:'
                ).replace(
                    'elif engine in ("unity-mono", "xna-fna"):',
                    'elif engine in ("godot", "gamemaker", "java") or '
                    'engine in ("unity-mono", "xna-fna"):')},
        }
        cand = Candidate(
            family=self.NAME, language="python", domain=self.DOMAIN,
            difficulty=rng.choice(self.DIFFICULTIES),
            task=("You are doing game-modding RECON on a SYNTHETIC install "
                  "manifest (educational pipeline data; no real games). Each "
                  "entry carries path, size, first-bytes hex and notable "
                  "strings. Implement classify_install(manifest) that returns "
                  "{'engine', 'loader', 'anti_cheat', 'online', 'route'}: "
                  "engine in {godot, unity-mono, unity-il2cpp, unreal, "
                  "xna-fna, gamemaker, java, unknown} from the distinctive "
                  "magic/marker evidence (GDPC pck, UnityFS, pak 0x5A6F12E1, "
                  "XNB+FNA.dll, FORM data.win, versions/*.jar, IL2CPP pair); "
                  "loader in {bepinex, ue4ss, tmodloader, fabric, smapi, "
                  "None}; anti_cheat in {battleye, eac, none}; online True "
                  "iff any engine string is OnlineSubsystemSteam/EOS_SDK/"
                  "PlayFab; route ladder: 'refuse-online' if anti-cheat AND "
                  "online, else 'loader-api' if a loader is present, else "
                  "'data' for godot/gamemaker/java, 'managed-patch' for "
                  "unity-mono/xna-fna, otherwise 'native-hook'. The tests "
                  "assert the exact classification of five planted installs."),
            expected_behavior=expected, code=_RECON_TEMPLATE, tests=tests,
            verify_method="executed",
            notes={"explain": explain, "kind": "recon",
                   "_bug_fns": bugs},
            tags=["game", "modding", "recon", "security"],
            variant="recon|" + "|".join(sorted({s[0] for s in picked})),
            seed=rng.randrange(2**31))
        return cand

    def make_buggy(self, rng: random.Random):
        # route_ladder_swapped only triggers when a data-route scenario
        # (godot/gamemaker/java without loader) is in the planted sample
        for _ in range(8):
            cand = self.generate(rng)
            bugs = cand.notes.get("_bug_fns") or {}
            if not bugs:
                continue
            kind = rng.choice(sorted(bugs))
            if kind == "route_ladder_swapped" and "'route': 'data'" not in cand.tests:
                continue
            buggy = bugs[kind]({"solution.py": cand.code})
            if buggy["solution.py"] == cand.code:
                continue
            return (Candidate(family=self.NAME, language="python",
                          domain=cand.domain, difficulty=cand.difficulty,
                          task=cand.task,
                          expected_behavior=cand.expected_behavior,
                          code=buggy["solution.py"], tests=cand.tests,
                          verify_method="executed",
                          notes={"bug_kind": kind,
                                 "correct_code": cand.code},
                          tags=cand.tags,
                          variant=cand.variant + f"|bug|{kind}",
                          seed=cand.seed),
                {"kind": kind, "problem": cand.variant,
                 "correct_code": cand.code, "tests": cand.tests,
                 "unit_notes": cand.notes.get("explain", {})})

    def review_variant(self, rng: random.Random):
        cand = self.generate(rng)
        issues = [
            {"kind": "performance", "severity": "low",
             "why": "the manifest is scanned once per rule group, so the "
                    "evidence lists are rebuilt several times",
             "better": "derive the path/head/string pools in a single pass "
                       "and reuse them for every rule"},
            {"kind": "maintainability", "severity": "medium",
             "why": "engine magics and loader paths are hard-coded literals "
                    "inside the branches",
             "better": "hoist them into module-level tables so new engines "
                       "are data additions, not code changes"},
            {"kind": "robustness", "severity": "medium",
             "why": "matching is case-insensitive, but separators are "
                    "normalized only for paths, not for string evidence",
             "better": "normalize both once at intake, then match on the "
                       "normalized form only"}]
        return (cand, issues)


# ================================================================ 2. backup
_BACKUP_TEMPLATE = '''import hashlib


def _sha(data: bytes) -> str:
    """sha256 hex digest of a save file's bytes."""
    return hashlib.sha256(data).hexdigest()


def snapshot_files(files: dict) -> dict:
    """Deep-copy the save folder ({path: bytes}) as a restore point."""
    return {p: bytes(d) for p, d in files.items()}


def diff_snapshots(base: dict, current: dict) -> list:
    """Ordered operations taking base -> current, with sha256 claims.

    Every op carries the hash it expects to find, so a restore can refuse
    to run against a folder that changed underneath it.
    """
    ops = []
    for p in sorted(set(base) | set(current)):
        if p not in base:
            ops.append({"op": "add", "path": p,
                        "new_sha": _sha(current[p])})
        elif p not in current:
            ops.append({"op": "remove", "path": p,
                        "old_sha": _sha(base[p])})
        elif _sha(base[p]) != _sha(current[p]):
            ops.append({"op": "change", "path": p,
                        "old_sha": _sha(base[p]),
                        "new_sha": _sha(current[p])})
    return ops


def restore_snapshot(current: dict, backup: dict, ops: list) -> dict:
    """Apply ops to current, rebuilding base content from the backup.

    Raises ValueError when current does not match the diff's sha256
    claims (the folder moved under us - never overwrite blindly).
    """
    out = dict(current)
    for o in ops:
        p = o["path"]
        if o["op"] == "add":
            if p not in out or _sha(out[p]) != o["new_sha"]:
                raise ValueError("unexpected state for " + p)
            del out[p]
        elif o["op"] == "remove":
            if p in out:
                raise ValueError("unexpected state for " + p)
            out[p] = bytes(backup[p])
        else:
            if p not in out or _sha(out[p]) != o["new_sha"]:
                raise ValueError("unexpected state for " + p)
            out[p] = bytes(backup[p])
    return out
'''


class GameSaveBackupFamily(Family):
    NAME = "game_save_backup"
    LANGUAGE = "python"
    DOMAIN = "engineering"
    DIFFICULTIES = ("intermediate", "advanced")
    SUPPORTS = ("explanation", "debugging", "testing")

    _SAVE_NAMES = ["player.dat", "world.bin", "profile.sav", "config.ini",
                   "quicksave.sav", "autobak.sav", "inventory.db"]
    _MOD_KEYS = ["hp", "gold", "level", "pos_x", "pos_y", "stamina"]

    def _saves(self, rng: random.Random, names: list[str]) -> dict:
        return {n: f"{k}={rng.randrange(0, 9999)};".encode()
                for n, k in zip(names, rng.sample(self._MOD_KEYS,
                                                  len(names)))}

    def generate(self, rng: random.Random) -> Candidate:
        base_names = rng.sample(self._SAVE_NAMES, rng.randint(4, 5))
        backup = self._saves(rng, base_names)
        current = {p: bytes(d) for p, d in backup.items()}
        mutated = rng.sample(base_names, rng.randint(1, 2))
        for p in mutated:
            new = f"{rng.choice(self._MOD_KEYS)}={rng.randrange(0, 9999)};".encode()
            while new == backup[p]:  # a no-op rewrite is not a change
                new = f"{rng.choice(self._MOD_KEYS)}={rng.randrange(0, 9999)};".encode()
            current[p] = new
        added = rng.choice([n for n in self._SAVE_NAMES if n not in base_names])
        current[added] = b"new=1;"
        # never remove a file we also mutated: the change op would be
        # swallowed by the remove op and the scenario loses its change
        removed = rng.choice([n for n in base_names if n not in mutated])
        del current[removed]
        # reference results (single source of truth for the tests)
        ref = {}
        exec(_BACKUP_TEMPLATE, ref)
        ops = ref["diff_snapshots"](backup, current)
        restored = ref["restore_snapshot"](current, backup, ops)
        tampered = dict(current)
        tampered[mutated[0]] = b"tampered=1;"
        change_ops = [o for o in ops if o["op"] == "change"]
        assert change_ops, "scenario must contain at least one change op"
        tests = (
            f"def run_tests():\n"
            f"    backup = {backup!r}\n"
            f"    current = {current!r}\n"
            f"    ops = diff_snapshots(backup, current)\n"
            f"    assert ops == {ops!r}\n"
            f"    restored = restore_snapshot(current, backup, ops)\n"
            f"    assert restored == backup\n"
            f"    assert diff_snapshots(backup, restored) == []\n"
            f"    tampered = dict(current)\n"
            f"    tampered[{mutated[0]!r}] = b'tampered=1;'\n"
            f"    try:\n"
            f"        restore_snapshot(tampered, backup, ops)\n"
            f"        assert False, 'stale diff must refuse to restore'\n"
            f"    except ValueError:\n"
            f"        pass\n")
        expected = ("Diff lists every add/remove/change with sha256 claims "
                    "in sorted path order; restore rebuilds the exact backup "
                    "content and refuses stale diffs whose claims no longer "
                    "match the folder.")
        explain = {
            "purpose": ("Back up saves before any modded launch, diff the "
                        "damage, and restore exactly - the modder's safety "
                        "net."),
            "approach": ("Snapshot copies bytes; diff emits hash-claimed ops "
                         "in sorted path order; restore verifies every claim "
                         "before overwriting."),
            "key_points": ["hash claims make restores refuse stale diffs",
                           "sorted paths give byte-stable diffs",
                           "restore pulls content only from the snapshot, "
                           "never from the live folder"],
            "big_o_time": "O(n) files per diff/restore",
            "big_o_space": "O(n) file bytes for the snapshot",
            "edge_cases": ["empty folder", "file replaced between diff and "
                           "restore", "same content re-saved (no op)"]}
        bugs = {
            "claim_skipped": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    "        else:\n            if p not in out or _sha(out[p]) != o[\"new_sha\"]:\n"
                    "                raise ValueError(\"unexpected state for \" + p)\n"
                    "            out[p] = bytes(backup[p])",
                    "        else:\n            if p not in out:\n"
                    "                raise ValueError(\"unexpected state for \" + p)\n"
                    "            out[p] = bytes(backup[p])")},
            "duplicate_paths": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    "for p in sorted(set(base) | set(current)):",
                    "for p in sorted(set(base)) + sorted(set(current)):")},
        }
        cand = Candidate(
            family=self.NAME, language="python", domain=self.DOMAIN,
            difficulty=rng.choice(self.DIFFICULTIES),
            task=("A modding session must never touch saves without a "
                  "safety net (snapshot -> diff -> restore, the `um backup` "
                  "model). Implement snapshot_files(files) returning a deep "
                  "byte copy of the folder, diff_snapshots(base, current) "
                  "returning the ordered op list "
                  "[{op: add|change|remove, path, old_sha?, new_sha?}] in "
                  "sorted path order where every op carries sha256 hex "
                  "claims, and restore_snapshot(current, backup, ops) that "
                  "verifies each claim against the live folder (raising "
                  "ValueError on any mismatch, including an 'add' whose file "
                  "changed after the diff) and rebuilds the exact backup "
                  "content from the snapshot. The tests restore a mutated "
                  "save folder byte-for-byte and refuse a tampered stale "
                  "diff."),
            expected_behavior=expected, code=_BACKUP_TEMPLATE, tests=tests,
            verify_method="executed",
            notes={"explain": explain, "kind": "backup",
                   "_bug_fns": bugs},
            tags=["game", "modding", "backup", "integrity"],
            variant=f"backup|{len(base_names)}|{removed}",
            seed=rng.randrange(2**31))
        return cand

    def make_buggy(self, rng: random.Random):
        cand = self.generate(rng)
        bugs = cand.notes.get("_bug_fns") or {}
        if not bugs:
            return None
        kind = rng.choice(sorted(bugs))
        buggy = bugs[kind]({"solution.py": cand.code})
        if buggy["solution.py"] == cand.code:
            return None
        return (Candidate(family=self.NAME, language="python",
                          domain=cand.domain, difficulty=cand.difficulty,
                          task=cand.task,
                          expected_behavior=cand.expected_behavior,
                          code=buggy["solution.py"], tests=cand.tests,
                          verify_method="executed",
                          notes={"bug_kind": kind,
                                 "correct_code": cand.code},
                          tags=cand.tags,
                          variant=cand.variant + f"|bug|{kind}",
                          seed=cand.seed),
                {"kind": kind, "problem": cand.variant,
                 "correct_code": cand.code, "tests": cand.tests,
                 "unit_notes": cand.notes.get("explain", {})})

    def review_variant(self, rng: random.Random):
        cand = self.generate(rng)
        issues = [
            {"kind": "performance", "severity": "medium",
             "why": "snapshot_files copies every file's full bytes into "
                    "memory, so large save folders double in RAM",
             "better": "copy into a staging directory on disk (or hash plus "
                       "hard-link) instead of materializing all bytes"},
            {"kind": "robustness", "severity": "medium",
             "why": "restore verifies 'add' and 'change' claims but trusts "
                    "'remove' claims without checking old_sha against the "
                    "snapshot itself",
             "better": "verify _sha(backup[p]) == o['old_sha'] for remove "
                       "ops too, so a corrupted snapshot is caught"},
            {"kind": "style", "severity": "low",
             "why": "the three op branches duplicate the claim-check shape",
             "better": "table-drive the checks: expected-present and "
                       "expected-hash per op kind"}]
        return (cand, issues)


# ================================================================= 3. lint
_LINT_TEMPLATE = '''import re

_KEY_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9]{20,}"),
    re.compile(r"ghp_[A-Za-z0-9]{30,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
]
_DECOMP = re.compile(r"\\b(?:FUN_|DAT_|sub_)[0-9A-Fa-f]{6,}\\b")
_DECOMP_HEADER = "decompiled with"


def lint_package(files: dict, game_hashes) -> dict:
    """Pre-release lint for a mod package ({path: {sha256, text?}}).

    FAIL: game_file (sha256 identical to a shipped game file), env_file
    (any .env), leaked_key (provider key pattern in text).
    WARN: decompiler_artifact (Ghidra/IDA names or headers),
    absolute_path (C:\\\\Users\\\\), missing_readme.
    Returns {"fail": sorted, "warn": sorted} with 'rule:path' entries.
    """
    fail = set()
    warn = set()
    if "README.md" not in files:
        warn.add("missing_readme:README.md")
    for path, meta in files.items():
        if meta["sha256"] in game_hashes:
            fail.add("game_file:" + path)
        if path.lower().endswith(".env"):
            fail.add("env_file:" + path)
        text = meta.get("text")
        if not text:
            continue
        if any(rx.search(text) for rx in _KEY_PATTERNS):
            fail.add("leaked_key:" + path)
        if _DECOMP.search(text) or _DECOMP_HEADER in text.lower():
            warn.add("decompiler_artifact:" + path)
        if "c:\\\\users\\\\" in text.lower():
            warn.add("absolute_path:" + path)
    return {"fail": sorted(fail), "warn": sorted(warn)}
'''


class GamePublishLintFamily(Family):
    NAME = "game_publish_lint"
    LANGUAGE = "python"
    DOMAIN = "security"
    DIFFICULTIES = ("intermediate", "advanced")
    SUPPORTS = ("explanation", "debugging", "testing", "security")

    _FILE_NAMES = ["main.tjs", "plugin.cfg", "assets/atlas.png.meta",
                   "scripts/spawn_logic.lua", "lang/en_us.json",
                   "shader/fog.frag", "docs/notes.md", "lib/core.dll"]
    _ENV_KEYS = ["sk-LiveAbCdEf0123456789abcd", "ghp_" + "AbC12" * 7,
                 "AKIA" + "J3X2QV7B4N9KD1M8ZP0F"]

    def generate(self, rng: random.Random) -> Candidate:
        import hashlib as _h
        dirty = rng.random() < 0.75
        names = rng.sample(self._FILE_NAMES, rng.randint(4, 6))
        if not any(n.endswith((".lua", ".json", ".md")) for n in names):
            names[-1] = rng.choice(["scripts/spawn_logic.lua",
                                    "lang/en_us.json", "docs/notes.md"])
        game_hashes = set()
        files = {}
        for i, p in enumerate(names):
            body = f"# {p}\nbuilt for the synthetic mod demo {i}\n"
            files[p] = {"sha256": _h.sha256(body.encode()).hexdigest(),
                        "text": body}
        if dirty:
            # planted FAIL 1: byte-identical game file
            game_body = b"GXPKG" + bytes(rng.randrange(256) for _ in range(64))
            ghash = _h.sha256(game_body).hexdigest()
            game_hashes.add(ghash)
            gp = f"assets/{rng.choice(['world.pkg', 'terrain.blk'])}"
            files[gp] = {"sha256": ghash, "text": None}
            # planted FAIL 2: .env file
            envp = rng.choice([".env", "config/.env"])
            envkey = rng.choice(self._ENV_KEYS)
            files[envp] = {"sha256": _h.sha256(envkey.encode()).hexdigest(),
                           "text": f"FAL_KEY={envkey}\n"}
            # planted FAIL 3: leaked key inside a text file
            kp = rng.choice([n for n in names if n.endswith((".lua", ".json", ".md"))])
            leak = rng.choice(self._ENV_KEYS)
            files[kp]["text"] += f"# helper key for tests: {leak}\n"
            files[kp]["sha256"] = _h.sha256(files[kp]["text"].encode()).hexdigest()
            # planted WARN: decompiler artifact
            dp_pool = [n for n in names
                       if n != kp and n.endswith((".lua", ".md"))]
            dp = rng.choice(dp_pool or [n for n in names if n != kp])
            sym = f"FUN_{rng.randrange(0x100000, 0xffffff):06x}"
            files[dp]["text"] += f"// {sym} calls the retail allocator\n"
            files[dp]["sha256"] = _h.sha256(files[dp]["text"].encode()).hexdigest()
            # planted WARN: absolute path
            ap = rng.choice([n for n in names if n.endswith(".cfg") or
                             n.endswith(".json")]) if any(
                n.endswith((".cfg", ".json")) for n in names) else names[0]
            files[ap]["text"] += "out_dir=C:\\Users\\dev\\AppData\\Local\\temp\n"
            files[ap]["sha256"] = _h.sha256(files[ap]["text"].encode()).hexdigest()
            warn_readme = rng.random() < 0.5
        else:
            warn_readme = rng.random() < 0.5
        if warn_readme:
            files["README.md"] = {"sha256": _h.sha256(b"readme").hexdigest(),
                                  "text": "install: drop into mods/\n"}
        ref = {}
        exec(_LINT_TEMPLATE, ref)
        report = ref["lint_package"](files, game_hashes)
        clean_files = {"README.md": files.get("README.md") or
                       {"sha256": _h.sha256(b"readme").hexdigest(),
                        "text": "readme\n"},
                       "assets/own_sprite.png": {"sha256": _h.sha256(b"s").hexdigest(),
                                                 "text": None},
                       "scripts/own.lua": {"sha256": _h.sha256(b"l").hexdigest(),
                                           "text": "-- own code only\n"}}
        clean_report = ref["lint_package"](clean_files, game_hashes)
        assert clean_report == {"fail": [], "warn": []}, "clean baseline broke"
        empty_repr = repr({"fail": [], "warn": []})
        tests = (
            f"def run_tests():\n"
            f"    files = {files!r}\n"
            f"    game_hashes = {game_hashes!r}\n"
            f"    assert lint_package(files, game_hashes) == {report!r}\n"
            f"    clean = {clean_files!r}\n"
            f"    assert lint_package(clean, game_hashes) == {empty_repr}\n")
        expected = ("The dirty package is reported with the exact sorted "
                    "fail/warn entries (game_file, env_file, leaked_key as "
                    "fails; decompiler_artifact, absolute_path, and "
                    "missing_readme as warns when planted); the clean "
                    "package reports nothing.")
        explain = {
            "purpose": ("Ship mods as your own code and assets only: catch "
                        "game files, leaked keys and decompiler artifacts "
                        "before release."),
            "approach": ("Set-accumulated rule hits normalized to "
                         "'rule:path', sorted for byte-stable reports."),
            "key_points": ["byte-identity is a hash membership question, "
                           "not a diff",
                           "FAIL and WARN are different severities: only "
                           "fails block release",
                           "text rules apply only to files that carry text"],
            "big_o_time": "O(files x rules)",
            "big_o_space": "O(violations)",
            "edge_cases": ["no README", "binary file with no text",
                           "same violation in many files",
                           "clean package"]}
        bugs = {
            "severity_swapped": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    "        if any(rx.search(text) for rx in _KEY_PATTERNS):\n"
                    "            fail.add(\"leaked_key:\" + path)",
                    "        if any(rx.search(text) for rx in _KEY_PATTERNS):\n"
                    "            warn.add(\"leaked_key:\" + path)")},
            "env_missed": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    'if path.lower().endswith(".env"):',
                    'if path.lower().endswith(".envx"):')},
        }
        cand = Candidate(
            family=self.NAME, language="python", domain=self.DOMAIN,
            difficulty=rng.choice(self.DIFFICULTIES),
            task=("Implement the pre-release lint every mod must pass "
                  "(the `um publish check` model). "
                  "lint_package(files, game_hashes) receives the package "
                  "as {path: {'sha256': hex, 'text': str|None}} and the set "
                  "of shipped-game-file hashes. Rules - FAIL: 'game_file' "
                  "when a file's sha256 is in game_hashes; 'env_file' when "
                  "the path ends with .env; 'leaked_key' when text matches "
                  r"sk-[A-Za-z0-9]{20,}, ghp_[A-Za-z0-9]{30,} or "
                  r"AKIA[0-9A-Z]{16}. "
                  "WARN: 'decompiler_artifact' when text matches "
                  r"\b(?:FUN_|DAT_|sub_)[0-9A-Fa-f]{6,}\b or contains "
                  "'decompiled with' (case-insensitive); 'absolute_path' "
                  "when text contains C:\\Users\\ (case-insensitive); "
                  "'missing_readme' when there is no README.md. Return "
                  "{'fail': [...], 'warn': [...]} with sorted, deduplicated "
                  "'rule:path' strings. Tests lint a planted dirty package "
                  "exactly and require a silent clean baseline."),
            expected_behavior=expected, code=_LINT_TEMPLATE, tests=tests,
            verify_method="executed",
            notes={"explain": explain, "kind": "lint",
                   "_bug_fns": bugs},
            tags=["game", "modding", "publish", "security", "lint"],
            variant=f"lint|{int(dirty)}|{len(files)}",
            seed=rng.randrange(2**31))
        return cand

    def make_buggy(self, rng: random.Random):
        # both bugs only trigger on dirty packages (leaked key / .env
        # planted); regenerate until the scenario carries them
        for _ in range(8):
            cand = self.generate(rng)
            if "leaked_key:" not in cand.tests:
                continue
            bugs = cand.notes.get("_bug_fns") or {}
            kind = rng.choice(sorted(bugs))
            buggy = bugs[kind]({"solution.py": cand.code})
            if buggy["solution.py"] == cand.code:
                continue
            return (Candidate(family=self.NAME, language="python",
                          domain=cand.domain, difficulty=cand.difficulty,
                          task=cand.task,
                          expected_behavior=cand.expected_behavior,
                          code=buggy["solution.py"], tests=cand.tests,
                          verify_method="executed",
                          notes={"bug_kind": kind,
                                 "correct_code": cand.code},
                          tags=cand.tags,
                          variant=cand.variant + f"|bug|{kind}",
                          seed=cand.seed),
                {"kind": kind, "problem": cand.variant,
                 "correct_code": cand.code, "tests": cand.tests,
                 "unit_notes": cand.notes.get("explain", {})})

    def review_variant(self, rng: random.Random):
        cand = self.generate(rng)
        issues = [
            {"kind": "maintainability", "severity": "medium",
             "why": "rule names, regexes and severity are tangled inside "
                    "one function body",
             "better": "drive the lint from a declarative rule table "
                       "(pattern, severity, message) so new rules cannot "
                       "touch control flow"},
            {"kind": "robustness", "severity": "low",
             "why": "hash membership assumes game_hashes is a set; a list "
                    "argument degrades to O(files x games)",
             "better": "coerce game_hashes = set(game_hashes) at entry"},
            {"kind": "performance", "severity": "low",
             "why": "each text is scanned by every rule independently",
             "better": "compile a combined scanner or short-circuit once a "
                       "file already accumulated every rule"}]
        return (cand, issues)


# ================================================================ 4. replay
_REPLAY_TEMPLATE = '''import struct


def q32(v: float) -> float:
    """Quantize to IEEE-754 single precision (the engine stores f32)."""
    return struct.unpack("<f", struct.pack("<f", v))[0]


GRAVITY = q32(-0.2)
BOOST_MULT = q32(1.21)


def step(state: dict, action=None) -> dict:
    """One frame of the toy projectile sim.

    The engine polls input AFTER physics, so an action observed on frame
    t takes effect on frame t+1 (a one-shot boost multiplies vx once).
    """
    state = dict(state)
    pending = state.get("pending_boost", False)
    state["pending_boost"] = False
    if action == "boost":
        state["pending_boost"] = True
    vx = state["vx"]
    if pending:
        vx = q32(vx * BOOST_MULT)
    vy = q32(state["vy"] + GRAVITY)
    x = q32(state["x"] + vx)
    y = q32(state["y"] + vy)
    state.update(x=x, y=y, vx=vx, vy=vy)
    return state


def replay_compare(step_fn, actions, initial, expected, tol=1e-6) -> dict:
    """Trace-replay oracle: run actions through step_fn and compare each
    frame against the recorded trace. Variables are checked in the order
    x, y, vx, vy; the first one to exceed tol pins first_divergence.
    """
    state = dict(initial)
    per_var = {"x": 0.0, "y": 0.0, "vx": 0.0, "vy": 0.0}
    first_divergence = None
    for t, action in enumerate(actions):
        state = step_fn(state, action)
        exp = expected[t]
        for var in ("x", "y", "vx", "vy"):
            err = abs(state[var] - exp[var])
            if err > per_var[var]:
                per_var[var] = err
            if err > tol and first_divergence is None:
                first_divergence = {"frame": t, "var": var}
    verdict = "match" if first_divergence is None else "mismatch"
    return {"per_var_max_err": per_var,
            "first_divergence": first_divergence,
            "verdict": verdict}
'''


def _ref_replay():
    """Execute the template once so ground truth shares its exact code."""
    ref = {}
    exec(_REPLAY_TEMPLATE, ref)
    return ref


class GameOracleReplayFamily(Family):
    NAME = "game_oracle_replay"
    LANGUAGE = "python"
    DOMAIN = "systems"
    DIFFICULTIES = ("advanced", "expert")
    SUPPORTS = ("explanation", "debugging", "testing", "trace")

    def generate(self, rng: random.Random) -> Candidate:
        ref = _ref_replay()
        q32, step = ref["q32"], ref["step"]
        vx0 = q32(round(rng.uniform(-6, 6), 3))
        while abs(vx0) < 0.05:  # keep the hidden buff clearly observable
            vx0 = q32(round(rng.uniform(-6, 6), 3))
        initial = {"x": round(rng.uniform(-10, 10), 3),
                   "y": round(rng.uniform(20, 90), 3),
                   "vx": vx0,
                   "vy": q32(round(rng.uniform(-2, 5), 3))}
        n = 10
        boost_at = rng.randrange(2, 6)
        actions = [None] * n
        actions[boost_at] = "boost"
        trace = []
        state = dict(initial)
        for t in range(n):
            state = step(state, actions[t])
            trace.append({k: state[k] for k in ("x", "y", "vx", "vy")})
        # planted hidden buff: from buff_frame the recorded vx is scaled
        # BEFORE the update (a hidden status active during those frames),
        # so x and vx both diverge at the buffed frame and the fixed
        # variable order decides which one is pinned.
        buff_frame = rng.randrange(3, 7)
        buff_mult = q32(1.5)
        buffed = []
        state = dict(initial)
        for t in range(n):
            if t >= buff_frame:
                state["vx"] = q32(state["vx"] * buff_mult)
            state = step(state, actions[t])
            buffed.append({k: state[k] for k in ("x", "y", "vx", "vy")})
        report_match = ref["replay_compare"](step, actions, initial,
                                             trace, 1e-6)
        assert report_match["verdict"] == "match"
        report_div = ref["replay_compare"](step, actions, initial,
                                           buffed, 1e-6)
        assert report_div["verdict"] == "mismatch"
        div_frame = report_div["first_divergence"]["frame"]
        div_var = report_div["first_divergence"]["var"]
        # the buff is active during the update, so x and vx both exceed
        # tol at the buffed frame; the fixed order (x, y, vx, vy) pins x
        assert div_frame == buff_frame and div_var == "x"
        boosted_vx = q32(q32(initial["vx"]) * q32(1.21))
        tests = (
            f"def run_tests():\n"
            f"    initial = {initial!r}\n"
            f"    actions = {actions!r}\n"
            f"    trace = {trace!r}\n"
            f"    s = dict(initial)\n"
            f"    s = step(s, actions[{boost_at}])\n"
            f"    assert s['vx'] == {initial['vx']!r}, 'boost acts on t+1'\n"
            f"    s = step(s, None)\n"
            f"    assert s['vx'] == {boosted_vx!r}\n"
            f"    r = replay_compare(step, actions, initial, trace, 1e-6)\n"
            f"    assert r['verdict'] == 'match'\n"
            f"    assert r['first_divergence'] is None\n"
            f"    buffed = {buffed!r}\n"
            f"    d = replay_compare(step, actions, initial, buffed, 1e-6)\n"
            f"    assert d['verdict'] == 'mismatch'\n"
            f"    assert d['first_divergence'] == "
            f"{report_div['first_divergence']!r}\n"
            f"    assert d['per_var_max_err']['vx'] > 1e-6\n")
        expected = ("The boost observed on frame t changes vx on frame t+1 "
                    "only; the clean replay matches bit-exactly (verdict "
                    "'match', zero errors), and the trace with the hidden "
                    f"vx buff diverges first at frame {div_frame} on "
                    f"variable {div_var!r} with verdict 'mismatch'.")
        explain = {
            "purpose": ("Replay a recorded gameplay trace through a ported "
                        "sim and pin the first divergence - the oracle that "
                        "catches wrong engine readings."),
            "approach": ("f32-quantized step semantics executed frame by "
                         "frame; per-variable max error with first "
                         "divergence pinned in fixed variable order."),
            "key_points": ["input polled after physics: action on frame t "
                           "lands on t+1",
                           "float32 constants must be quantized or the "
                           "replay drifts from the engine",
                           "the first divergence names the first wrong "
                           "variable, which localizes the bug"],
            "big_o_time": "O(frames x vars)",
            "big_o_space": "O(1) beyond the trace",
            "edge_cases": ["boost on the last frame", "hidden buffs the "
                           "port does not model", "tolerance vs bit equality"]}
        bugs = {
            "same_frame_boost": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    "    pending = state.get(\"pending_boost\", False)\n"
                    "    state[\"pending_boost\"] = False\n"
                    "    if action == \"boost\":\n"
                    "        state[\"pending_boost\"] = True",
                    "    pending = action == \"boost\"")},
            "var_order_swapped": lambda fs: {"solution.py":
                fs["solution.py"].replace(
                    'for var in ("x", "y", "vx", "vy"):',
                    'for var in ("vx", "x", "y", "vy"):')},
        }
        cand = Candidate(
            family=self.NAME, language="python", domain=self.DOMAIN,
            difficulty=rng.choice(self.DIFFICULTIES),
            task=("Modders verify ports by replaying real traces through "
                  "them (the trace-replay oracle). Implement the toy f32 "
                  "sim and the oracle exactly as specified. step(state, "
                  "action): one frame of a projectile - gravity GRAVITY = "
                  "q32(-0.2) added to vy, then x += vx, y += vy, every "
                  "intermediate quantized through q32() to single "
                  "precision. Input is polled AFTER physics, so action == "
                  "'boost' observed on frame t is stored as a pending flag "
                  "and multiplies vx by BOOST_MULT = q32(1.21) exactly "
                  "once on frame t+1. replay_compare(step_fn, actions, "
                  "initial, expected, tol=1e-6): run the actions, compare "
                  "each frame with the recorded trace, track per-variable "
                  "max abs error for x, y, vx, vy (checked in that order) "
                  "and pin first_divergence = {'frame': t, 'var': v} at "
                  "the first error above tol; return {'per_var_max_err', "
                  "'first_divergence', 'verdict'}. Tests boost once and "
                  "assert t+1 semantics, a bit-exact 'match' replay, and a "
                  "hidden-buff trace whose first divergence is pinned."),
            expected_behavior=expected, code=_REPLAY_TEMPLATE, tests=tests,
            verify_method="executed",
            notes={"explain": explain, "kind": "replay",
                   "_bug_fns": bugs},
            tags=["game", "modding", "oracle", "replay", "determinism"],
            variant=f"replay|{boost_at}|{buff_frame}",
            seed=rng.randrange(2**31))
        return cand

    def make_buggy(self, rng: random.Random):
        cand = self.generate(rng)
        bugs = cand.notes.get("_bug_fns") or {}
        if not bugs:
            return None
        kind = rng.choice(sorted(bugs))
        buggy = bugs[kind]({"solution.py": cand.code})
        if buggy["solution.py"] == cand.code:
            return None
        return (Candidate(family=self.NAME, language="python",
                          domain=cand.domain, difficulty=cand.difficulty,
                          task=cand.task,
                          expected_behavior=cand.expected_behavior,
                          code=buggy["solution.py"], tests=cand.tests,
                          verify_method="executed",
                          notes={"bug_kind": kind,
                                 "correct_code": cand.code},
                          tags=cand.tags,
                          variant=cand.variant + f"|bug|{kind}",
                          seed=cand.seed),
                {"kind": kind, "problem": cand.variant,
                 "correct_code": cand.code, "tests": cand.tests,
                 "unit_notes": cand.notes.get("explain", {})})

    def review_variant(self, rng: random.Random):
        cand = self.generate(rng)
        issues = [
            {"kind": "robustness", "severity": "medium",
             "why": "errors are absolute, so a large-magnitude variable "
                    "masks a relative drift on a small one",
             "better": "also report err / max(1, |expected|) and pin the "
                       "divergence on the relative breach"},
            {"kind": "performance", "severity": "low",
             "why": "replay_compare deep-copies state via step and keeps "
                    "only the running frame, which is fine, but the trace "
                    "itself is materialized by the caller",
             "better": "accept any iterable of expected frames so long "
                       "traces can stream"},
            {"kind": "style", "severity": "low",
             "why": "variable order and tolerance defaults are hard-coded "
                    "inside the comparator",
             "better": "hoist VAR_ORDER and DEFAULT_TOL to module level "
                       "so harnesses share one contract"}]
        return (cand, issues)


register(globals(), GameEngineReconFamily)
register(globals(), GameSaveBackupFamily)
register(globals(), GamePublishLintFamily)
register(globals(), GameOracleReplayFamily)
